routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TaskStatusController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\LabelController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (): \Illuminate\View\View {
    return view('welcome');
});

Auth::routes();

Route::resource('task_statuses', TaskStatusController::class);

Route::resource('tasks', TaskController::class);

Route::resource('labels', LabelController::class);

app/Models/Label.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Label extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'description'];

    public function tasks(): BelongsToMany
    {
        return $this->belongsToMany(Task::class, 'task_label');
    }
}

app/Http/Controllers/LabelController.php
<?php

namespace App\Http\Controllers;

use App\Models\Label;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class LabelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $labels = Label::all();
        return view('label.index', compact('labels'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $label = new Label();
        return view('label.create', compact('label'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|unique:labels',
            'description' => 'nullable|string',
        ]);

        Label::create($request->all());
        flash(__('interface.labels.created'))->success();
        return redirect()->route('labels.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Label  $label
     * @return \Illuminate\View\View
     */
    public function edit(Label $label)
    {
        return view('label.edit', compact('label'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Label  $label
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Label $label)
    {
        $request->validate([
            'name' => [
                'required',
                'string',
                Rule::unique('labels')->ignore($label)
            ],
            'description' => 'nullable|string',
        ]);

        $label->fill($request->all());
        $label->save();

        flash(__('interface.labels.updated'))->success();
        return redirect()->route('labels.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Label  $label
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Label $label)
    {
        if ($label->tasks()->exists()) {
            flash(__('interface.labels.exists'))->error();
            return redirect()->back();
        }
        $label->delete();
        flash(__('interface.labels.destroyed'))->success();
        return redirect()->route('labels.index');
    }
}

resources/views/label/create.blade.php
@extends('layouts.app')

@section('content')
    <h1 class="mb-5">
        {{ __('interface.labels.create') }}
    </h1>
    {{ Form::model($label, [
        'url' => route('labels.store'),
        'class' => 'w-50'])
    }}
        @include('label.form')
        {{ Form::submit(__('interface.create'), ['class' => 'btn btn-primary']) }}
    {{ Form::close() }}
@endsection

resources/views/label/edit.blade.php
@extends('layouts.app')

@section('content')
    <h1 class="mb-5">
        {{ __('interface.labels.edit') }}
    </h1>
    {{ Form::model($label, [
        'url' => route('labels.update', $label),
        'class' => 'w-50',
        'method' => 'PATCH'])
    }}
        @include('label.form')
        {{ Form::submit(__('interface.update'), ['class' => 'btn btn-primary']) }}
    {{ Form::close() }}
@endsection

resources/views/label/form.blade.php
@if ($errors->any())
    <div>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<div class="form-group">
    {{ Form::label('name', __('interface.name')) }}
    {{ Form::text('name', $label->name, ['class' => 'form-control']) }}
</div>
<div class="form-group">
    {{ Form::label('description', __('interface.description')) }}
    {{ Form::textarea('description', $label->description, ['class' => 'form-control', 'rows' => '10']) }}
</div>

resources/views/label/index.blade.php
@extends('layouts.app')

@section('content')
    <h1 class="mb-5">{{ __('interface.labels.name') }}</h1>
    @auth
        <a href="{{ route('labels.create') }}" class="btn btn-primary">{{ __('interface.labels.create') }}</a>
    @endauth
    <table class="table mt-2">
        <thead>
            <tr>
                <th>{{ __('interface.id') }}</th>
                <th>{{ __('interface.name') }}</th>
                <th>{{ __('interface.description') }}</th>
                <th>{{ __('interface.created_at') }}</th>
                @auth
                    <th>{{ __('interface.actions') }}</th>
                @endauth
            </tr>
        </thead>
        <tbody>
            @foreach($labels as $label)
                <tr>
                    <td>{{ $label->id }}</td>
                    <td>{{ $label->name }}</td>
                    <td>{{ $label->description }}</td>
                    <td>{{ $label->created_at->format('d.m.Y') }}</td>
                    @auth
                        <td>
                            <a href="{{ route('labels.destroy', $label) }}" class="text-danger" data-confirm="{{ __('interface.are_you_sure') }}" data-method="delete" rel="nofollow">
                                {{ __('interface.destroy') }}
                            </a>
                            <a href="{{ route('labels.edit', $label) }}">
                                {{ __('interface.edit') }}
                            </a>
                        </td>
                    @endauth
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection