routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TaskStatusController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\LabelController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (): \Illuminate\View\View {
    return view('welcome');
});

Auth::routes();

Route::resource('task_statuses', TaskStatusController::class);

Route::resource('tasks', TaskController::class);

Route::resource('labels', LabelController::class);

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Task extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'description', 'status_id', 'assigned_to_id'];

    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by_id');
    }

    public function status(): BelongsTo
    {
        return $this->belongsTo(TaskStatus::class);
    }

    public function performer(): BelongsTo
    {
        return $this->belongsTo(User::class, 'assigned_to_id');
    }

    public function labels(): BelongsToMany
    {
        return $this->belongsToMany(Label::class, 'task_label');
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Models\Task;
use App\Models\TaskStatus;
use App\Models\User;
use App\Models\Label;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Auth;
use Spatie\QueryBuilder\QueryBuilder;
use Spatie\QueryBuilder\AllowedFilter;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $tasks = QueryBuilder::for(Task::class)
            ->allowedFilters(
                [
                    AllowedFilter::exact('status_id'),
                    AllowedFilter::exact('created_by_id'),
                    AllowedFilter::exact('assigned_to_id')
                ]
            )
            ->get();
        session()->put('filter', \request()->input('filter'));
        $taskStatuses = TaskStatus::pluck('name', 'id');
        $users = User::pluck('name', 'id');
        return view('task.index', compact('tasks', 'taskStatuses', 'users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $task = new Task();
        $taskStatuses = TaskStatus::pluck('name', 'id');
        $users = User::pluck('name', 'id');
        $labels = Label::pluck('name', 'id');
        return view('task.create', compact('task', 'users', 'taskStatuses', 'labels'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => "required|string|unique:tasks",
            'description' => 'nullable|string|required',
            'assigned_to_id' => 'nullable|exists:users,id',
            'status_id' => 'required|exists:task_statuses,id',
            'labels.*' => 'exists:labels,id'
        ]);
        $task = new Task();
        $task->creator()->associate(Auth::user());
        $task->fill($request->all());
        $task->save();
        $task->labels()->sync($request->input('labels'));
        flash(__('interface.tasks.created'))->success();
        return redirect()->route('tasks.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\View\View
     */
    public function show(Task $task)
    {
        $statusName = optional($task->status)->name;
        $labels = $task->labels()->orderBy('name')->get();
        return view('task.show', compact('task', 'statusName', 'labels'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\View\View
     */
    public function edit(Task $task)
    {
        $taskStatuses = TaskStatus::pluck('name', 'id');
        $users = User::pluck('name', 'id');
        $labels = Label::pluck('name', 'id');
        return view('task.edit', compact('task', 'taskStatuses', 'users', 'labels'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Task $task)
    {
        $request->validate([
            'name' => [
                'required',
                'string',
                Rule::unique('tasks')->ignore($task)
            ],
            'description' => 'nullable|string',
            'status_id' => 'required|exists:task_statuses,id',
            'assigned_to_id' => 'nullable|exists:users,id',
            'labels.*' => 'exists:labels,id'
        ]);
        $task->fill($request->all());
        $task->save();
        $task->labels()->sync($request->input('labels'));
        flash(__('interface.tasks.updated'))->success();
        return redirect()->route('tasks.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Task $task)
    {
        $task->labels()->detach();
        $task->delete();
        flash(__('interface.tasks.destroyed'))->success();
        return redirect()->route('tasks.index');
    }
}

resources/views/task/create.blade.php
@extends('layouts.app')

@section('content')
    <h1 class="mb-5">
        {{ __('interface.tasks.create') }}
    </h1>
    {{ Form::model($task, [
        'url' => route('tasks.store'),
        'class' => 'w-50'])
    }}
        @include('task.form')
        {{ Form::submit(__('interface.create'), ['class' => 'btn btn-primary']) }}
    {{ Form::close() }}
@endsection

resources/views/task/edit.blade.php
@extends('layouts.app')

@section('content')
    <h1 class="mb-5">
        {{ __('interface.tasks.edit') }}
    </h1>
    {{ Form::model($task, [
    'url' => route('tasks.update', $task),
    'method' => 'PATCH',
    'class' => 'w-50'])
    }}
        @include('task.form')
        {{ Form::submit(__('interface.update'), ['class' => 'btn btn-primary']) }}
    {{ Form::close() }}
@endsection

resources/views/task/form.blade.php
@if ($errors->any())
    <div>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<div class="form-group">
    {{ Form::label('name', __('interface.name')) }}
    {{ Form::text('name', $task->name, ['class' => 'form-control']) }}
</div>
<div class="form-group">
    {{ Form::label('description', __('interface.description')) }}
    {{ Form::textarea('description', $task->description, ['class' => 'form-control', 'rows' => '10']) }}
</div>
<div class="form-group">
    {{ Form::label('status_id', __('interface.status')) }}
    {{ Form::select('status_id', $taskStatuses, null, ['class' => 'form-control', 'placeholder' => '---------']) }}
</div>
<div class="form-group">
    {{ Form::label('assigned_to_id', __('interface.performer')) }}
    {{ Form::select('assigned_to_id', $users, null, ['class' => 'form-control', 'placeholder' => '---------']) }}
</div>
<div class="form-group">
    {{ Form::label('labels', __('interface.labels.name')) }}
    {{ Form::select('labels[]', $labels, null, ['class' => 'form-control', 'placeholder' => ' ', 'multiple' => true]) }}
</div>

resources/views/task/index.blade.php
@extends('layouts.app')

@section('content')
    <h1 class="mb-5">{{ __('interface.tasks.name') }}</h1>
    <div class="d-flex">
    <div>
        {{ Form::open(['url' => route('tasks.index'), 'method' => 'GET', 'class' => 'form-inline']) }}
            {{ Form::select('filter[status_id]', $taskStatuses, session('filter')['status_id'] ?? null, ['class' => 'form-control mr-2', 'placeholder' => __('interface.status')]) }}
            {{ Form::select('filter[created_by_id]', $users, session('filter')['created_by_id'] ?? null, ['class' => 'form-control mr-2', 'placeholder' => __('interface.creator')]) }}
            {{ Form::select('filter[assigned_to_id]', $users, session('filter')['assigned_to_id'] ?? null, ['class' => 'form-control mr-2', 'placeholder' => __('interface.performer')]) }}
            {{ Form::submit(__('interface.apply'), ['class' => 'btn btn-outline-primary']) }}
        {{ Form::close() }}
    </div>
    @auth
        <a href="{{ route('tasks.create') }}" class="btn btn-primary ml-auto">{{ __('interface.tasks.create') }}</a>
    @endauth
</div>
    <table class="table mt-2">
        <thead>
            <tr>
                <th>{{ __('interface.id') }}</th>
                <th>{{ __('interface.status') }}</th>
                <th>{{ __('interface.name') }}</th>
                <th>{{ __('interface.creator') }}</th>
                <th>{{ __('interface.performer') }}</th>
                <th>{{ __('interface.created_at') }}</th>
                @auth
                    <th>{{ __('interface.actions') }}</th>
                @endauth
            </tr>
        </thead>
        <tbody>
            @foreach($tasks as $task)
                <tr>
                    <td>{{ $task->id }}</td>
                    <td>{{ optional($task->status)->name }}</td>
                    <td><a href="{{route('tasks.show', $task)}}">{{$task->name}}</a></td>
                    <td>{{ $task->creator->name }}</td>
                    <td>{{optional($task->performer)->name}}</td>
                    <td>{{ $task->created_at->format('d.m.Y') }}</td>
                    @auth
                        <td>
                            @if($task->created_by_id == Auth::id())
                                <a href="{{route('tasks.destroy', $task)}}"
                                    data-confirm="{{ __('messages.alert.confirm') }}"
                                    data-method="delete"
                                    rel="nofollow"
                                    class="text-danger">
                                    {{ __('interface.destroy') }}
                                </a>
                            @endif
                            <a href="{{ route('tasks.edit', $task) }}">
                                {{ __('interface.edit') }}
                            </a>
                        </td>
                    @endauth
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection

resources/views/task/show.blade.php
@extends('layouts.app')

@section('content')
    <h1 class="mb-5">
        {{ __('interface.tasks.show') }}{{ $task->name}}
        <a href="{{ route('tasks.edit', $task) }}">⚙</a>
    </h1>
    <p>{{ __('interface.name') }}: {{ $task->name }}</p>
    <p>{{ __('interface.status') }}: {{ $statusName }}</p>
    <p>{{ __('interface.description') }}: {{ $task->description }}</p>
    <p>{{__('interface.labels.name')}}: </p>
    @if ($labels)    
        <ul>
            @foreach ($labels as $label)
            <li>{{$label->name}}</li>
            @endforeach
        </ul>
    @endif
@endsection